### ISSUE TITLE
Conan chooses incorrect boost version

### ISSUE THREAD

**Issue by cassava** [eclipse/cloe#11]
When following the installation instructions given by `README.md` on a clean machine,
we get a conflict of boost versions.

```console
$ conan create . cloe/develop --build=missing --build=cloe -o cloe:with_vtd=False
Exporting package recipe
cloe/0.18.0-nightly@cloe/develop: The stored package has not changed
cloe/0.18.0-nightly@cloe/develop: Exported revision: 1cb07a17e0129777b9e4b5947a53bec6
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=10
os=Linux
os_build=Linux
[options]
cloe:with_vtd=False
[build_requires]
[env]

WARN: fable/1.0.0@cloe/develop: requirement boost/[>=1.65.1] overridden by cloe-runtime/0.18.0-nightly@cloe/develop to boost/1.75.0
WARN: fable/1.0.0@cloe/develop: requirement boost/[>=1.65.1] overridden by cloe-runtime/0.18.0-nightly@cloe/develop to boost/1.75.0
ERROR: Conflict in cpp-netlib/0.13.0@cloe/stable:
    'cpp-netlib/0.13.0@cloe/stable' requires 'boost/1.69.0' while 'cloe-runtime/0.18.0-nightly@cloe/develop' requires 'boost/1.75.0'.
    To fix this conflict you need to override the package 'boost' in your root package.
make[1]: *** [Makefile.package:148: package] Error 1
make: *** [Makefile.all:222: package] Error 2
```

We have the following dependency tree:
- `cloe`
  - `cloe-runtime` requires `boost/[>=1.65.1]`
    - `fable` requires `boost/[>=1.65.1]`
  - `cloe-models` requires `boost/[>=1.65.1]`
    - `cloe-runtime`
  - `cloe-engine`
    - `cloe-oak`
      - `cpp-netlib` requires `boost/[>=1.65.0 <1.70]`
    - `cloe-runtime`
    - `cloe-models`

---

We can simplify the dependency tree by just building `cloe-engine`:
- `cloe-engine`
  - `cloe-oak`
    - `cpp-netlib` requires `boost/[>=1.65.0 <1.70]`
  - `cloe-runtime` requires `boost/[>=1.65.1]`
  - `cloe-models` requires `boost/[>=1.65.1]`

Trying to build this gives us:
```console
$ conan create . cloe/develop --build=missing --build=cloe-engine
WARN: fable/1.0.0@cloe/develop: requirement boost/[>=1.65.1] overridden by cloe-runtime/0.18.0-nightly@cloe/develop to boost/1.75.0
ERROR: Conflict in cpp-netlib/0.13.0@cloe/stable:
    'cpp-netlib/0.13.0@cloe/stable' requires 'boost/1.69.0' while 'cloe-models/0.18.0-nightly@cloe/develop' requires 'boost/1.75.0'.
    To fix this conflict you need to override the package 'boost' in your root package.
make: *** [../Makefile.package:148: package] Error 1
```

**Comment by tobifalk** [comment]
I think [this posting](https://github.com/conan-io/conan/issues/4753#issuecomment-481663245) is highly relevant for the issue. We are using `build_requires` for `cloe-engine`'s dependencies `cloe-oak`, `cloe-runtime`, `cloe-models`. I guess I need to sit down and understand the suggested solutions better.

**Comment by tobifalk** [comment]
After going through the [Conan documentation on version ranges](https://docs.conan.io/en/latest/versioning/version_ranges.html) and some of the dependency graph related issues (especially [this one](https://github.com/conan-io/conan/issues/6215#issuecomment-564958319)), it seems that this problem is related to a known limitation of Conan.
The only near-term workaround that would fix the Cloe build is to impose the cpp-netlib boost dependency from the root package, i.e. cloe-engine (as stated in the error message). For that, I have created #20 and a corresponding pull request.

For future reference, I created [this minimal package setup](https://github.com/tobifalk/debug/tree/main/conan/dependency_graph/diamond_version_range) including visualizations of the desired and actual dependency graph as interpreted by conan v1.33.0
